[package]
name = "ipmpsc"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
bincode = "1"
tempfile = "3"
memmap = "0.7"
libc = "0.2"
failure = "0.1"

[dev-dependencies]
proptest = "0.9"
